[package]
name = "desktop_kana_cli"
version = "1.0.0"
authors = ["Tom Raistrick <t.raistrick@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
text_io = "0.1.8"
regex = "1.3.9"
rand = "0.7.3"